<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use AppBundle\Entity\CanalVirtual;
use Herrera\Json\Exception\Exception;

/**
 * CanalVirtualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanalVirtualRepository extends EntityRepository
{

    function getCanalesVirtualesByEnsayoId($id) {
        $sqlCanalVirtual = "SELECT * FROM canal_virtual WHERE ensayo_id='$id'";

        try {
            $em = $this->getEntityManager();
            $stmt = $em->getConnection()->prepare($sqlCanalVirtual);
            $stmt->execute();
            $arrayQueryResult = $stmt->fetchAll();
        }catch (\Exception $e) {
            throw new NotFoundHttpException("Error en recolección de canales virtuales");
        }

        return $arrayQueryResult;
    }


}
