<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Curva;

/**
 * CurvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurvaRepository extends EntityRepository
{

    public function getListadoCurvas()
    {
        $sqlListadoCurvas = "SELECT * FROM curva GROUP BY nombre ORDER BY id ASC";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sqlListadoCurvas);
        $stmt->execute();
        $arrayQueryResult = $stmt->fetchAll();

        return $arrayQueryResult;
    }

}
