# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers


    providers:
        my_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    device:
                        password: INTI1957
                        roles: 'ROLE_DEVICE'
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: my_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: login


    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/logdata, roles: ROLE_DEVICE }
            - { path: ^/checkEnsayoStart, roles: ROLE_DEVICE }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER }


    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER, ROLE_DEVICE]


