# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers


    providers:
        chain_provider:
            chain:
                providers: [in_memory, my_db_provider]
        my_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    superadmin:
                        password: INTI1991
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        api:
            anonymous: ~
            pattern:   ^/api
            provider: my_db_provider
            guard:
                authenticators:
                    - app.token_authenticator
            stateless: true

        front_end:
            anonymous: ~
            pattern: ^/
            provider: my_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: login



    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: ROLE_DEVICE }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER }


    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER, ROLE_DEVICE]


